# Site settings
title: Hahn's Think Space
email: xingshihan@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hahn的思维殿堂
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hahn1994.github.io/" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
github:   hahn1994
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
