# Site settings
title: Hahn's MindPlace
email: xingshihan@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hahn Xing的思维殿堂
  个人随笔、技术笔记、黑鸡汤
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hahn1994.github.io/" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
weibo:    hahn1994
github:   hahn1994
# codepen:  username
# dribbble: username


# Comment
disqus_shortname: hahn1994


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed
gems:
  - jekyll-sitemap

# Global settings
encoding: UTF-8
timezone: Asia/Shanghai