# Global settings
encoding:          UTF-8
timezone:          Asia/Shanghai

# Site settings
title:             Hahn's MindPlace
email:             xingshihan@hotmail.com
description:       > 
                   Hahn Xing的思维殿堂
                   个人随笔、技术笔记、黑鸡汤
baseurl:           "" # the subpath of your site, e.g. /blog/
url:               "http://hahn1994.github.io/" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter:            'category'


# Social account
weibo:              hahn1994
github:             hahn1994
# twitter:          username
# codepen:          username
# dribbble:         username


# Comment
disqus_shortname:   hahn1994


# Google Analytics
# google_analytics: tracking_ID


# Build settings
permalink:          /:categories/:title.html
markdown:           kramdown
highlighter:        rouge
markdown_ext:       "markdown,mkdown,mkdn,mkd,md"
kramdown:
  input:            GFM
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed
gems:
  - jekyll-sitemap
  - jekyll-mentions
jekyll-mentions:
    base_url:       https://github.com
